#cloud-config
package_update: true
package_upgrade: true
power_state:
  delay: "now"
  mode: "reboot"
  message: "Rebooting to apply updates"
  timeout: 60

write_files:
  - path: /etc/netplan/60-reserved-ipv6.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            addresses:
              - "2a03:b0c0:2:f0:0:1:bc12:9001/128"
packages:
  - curl
  - git
  - tmux
  - htop
  - ca-certificates

runcmd:
- install -m 0755 -d /etc/apt/keyrings
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
- chmod a+r /etc/apt/keyrings/docker.asc
- echo "deb [signed-by=/etc/apt/keyrings/docker.asc arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" > /etc/apt/sources.list.d/docker.list
- apt update
- apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
