from alpine:latest

run apk update
run apk add bash curl neovim git openssh tmux docker bash-completion docker-bash-completion

workdir /config
run git clone https://github.com/erikbergsten/vimrc.git
workdir /config/vimrc
run mkdir /root/.config
run bash install.sh
copy .profile /root/.profile
copy .gitconfig /root/.gitconfig

env SSH_AUTH_SOCK=/ssh-agent
env BASH=/bin/bash

workdir /work
entrypoint ["/bin/bash"]
